version: "3.1"

services:
  viper-bug-with-sourced-env:
    container_name: viper-bug
    image: golang:1.16-alpine
    volumes:
      - ${PWD}/:/app
    working_dir: /app
    env_file:
      - ./.env
    command: go run main.go
  viper-bug-with-config-env:
    container_name: viper-bug
    image: golang:1.16-alpine
    volumes:
      - ${PWD}/:/app
    working_dir: /app
    env_file:
      - ./.env
    command: go run main.go
